DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS items;

CREATE TABLE IF NOT EXISTS users(
	id CHAR(4) NOT NULL,
	pwd NVARCHAR(10),
	name NVARCHAR(20)
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS items(
	id INT(10) AUTO_INCREMENT PRIMARY KEY,
	name NVARCHAR(20),
	price INT(10),
	regdate DATE
);

ALTER TABLE items AUTO_INCREMENT = 1000;

INSERT INTO users(id, name) VALUES('id01','james');
INSERT INTO users VALUES('id02','12345','smith');
SELECT * FROM users;

INSERT INTO items VALUES(NULL,'item01',10000,CURRENT_DATE);
INSERT INTO items VALUES(NULL,'item02',16000,CURRENT_DATE);
INSERT INTO items VALUES(NULL,'item03',1000,CURRENT_DATE);
INSERT INTO items VALUES(NULL,'item04',3000,CURRENT_DATE);
INSERT INTO items VALUES(NULL,'item05',900,CURRENT_DATE);
INSERT INTO items VALUES(NULL,'item06',20000,CURRENT_DATE);
