DROP TABLE IF EXISTS item;

CREATE TABLE item
(	
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name NVARCHAR(10) NOT NULL,
	code CHAR(5),
	price INT,
	rate FLOAT,
	regdate DATE
);

ALTER TABLE item AUTO_INCREMENT = 1000;
INSERT INTO item VALUES(NULL,'상품이름은바지입니다','1111',5,5.2,CURRENT_DATE);
INSERT INTO item VALUES(NULL,'item02','1111',3,5.2,CURRENT_DATE);
SELECT * FROM item;

